<?php
$language_code = array(
	'English' => 'en',
	'Afar' => 'aa',
	'Abkhazian' => 'ab',
	'Afrikaans' => 'af',
	'Akan' => 'ak',
	'Albanian' => 'sq',
	'Amharic' => 'am',
	'Arabic' => 'ar',
	'Aragonese' => 'an',
	'Armenian' => 'hy',
	'Assamese' => 'as',
	'Avaric' => 'av',
	'Avestan' => 'ae',
	'Aymara' => 'ay',
	'Azerbaijani' => 'az',
	'Bashkir' => 'ba',
	'Bambara' => 'bm',
	'Basque' => 'eu',
	'Belarusian' => 'be',
	'Bengali' => 'bn',
	'Bihari' => 'bh',
	'Bislama' => 'bi',
	'Bosnian' => 'bs',
	'Breton' => 'br',
	'Bulgarian' => 'bg',
	'Burmese' => 'my',
	'Catalan' => 'ca',
	'Valencian' => 'ca',
	'Chamorro' => 'ch',
	'Chechen' => 'ce',
	'Chinese' => 'zh',
	'Church Slavic' => 'cu',
	'Old Slavonic' => 'cu',
	'Church Slavonic' => 'cu',
	'Old Bulgarian' => 'cu',
	'Old Church Slavonic' => 'cu',
	'Chuvash' => 'cv',
	'Cornish' => 'kw',
	'Corsican' => 'co',
	'Cree' => 'cr',
	'Czech' => 'cs',
	'Danish' => 'da',
	'Divehi' => 'dv',
	'Dutch' => 'nl',
	'Flemish' => 'nl',
	'Dzongkha' => 'dz',
	'Esperanto' => 'eo',
	'Estonian' => 'et',
	'Ewe' => 'ee',
	'Faroese' => 'fo',
	'Fijian' => 'fj',
	'Finnish' => 'fi',
	'French' => 'fr',
	'Frisian' => 'fy',
	'Fulah' => 'ff',
	'Georgian' => 'ka',
	'German' => 'de',
	'Gaelic' => 'gd',
	'Scottish Gaelic' => 'gd',
	'Irish' => 'ga',
	'Galician' => 'gl',
	'Manx' => 'gv',
	'Greek' => 'el',
	'Guarani' => 'gn',
	'Gujarati' => 'gu',
	'Haitian' => 'ht',
	'Haitian Creole' => 'ht',
	'Hausa' => 'ha',
	'Hebrew' => 'he',
	'Herero' => 'hz',
	'Hindi' => 'hi',
	'Hiri Motu' => 'ho',
	'Hungarian' => 'hu',
	'Igbo' => 'ig',
	'Icelandic' => 'is',
	'Ido' => 'io',
	'Sichuan Yi' => 'ii',
	'Inuktitut' => 'iu',
	'Interlingue' => 'ie',
	'Interlingua (International Auxiliary Language Association)' => 'ia',
	'Indonesian' => 'id',
	'Inupiaq' => 'ik',
	'Italian' => 'it',
	'Javanese' => 'jv',
	'Japanese' => 'ja',
	'Kalaallisut' => 'kl',
	'Greenlandic' => 'kl',
	'Kannada' => 'kn',
	'Kashmiri' => 'ks',
	'Kanuri' => 'kr',
	'Kazakh' => 'kk',
	'Khmer' => 'km',
	'Kikuyu' => 'ki',
	'Gikuyu' => 'ki',
	'Kinyarwanda' => 'rw',
	'Kirghiz' => 'ky',
	'Komi' => 'kv',
	'Kongo' => 'kg',
	'Korean' => 'ko',
	'Kuanyama' => 'kj',
	'Kwanyama' => 'kj',
	'Kurdish' => 'ku',
	'Lao' => 'lo',
	'Latin' => 'la',
	'Latvian' => 'lv',
	'Limburgan' => 'li',
	'Limburger' => 'li',
	'Limburgish' => 'li',
	'Lingala' => 'ln',
	'Lithuanian' => 'lt',
	'Luxembourgish' => 'lb',
	'Letzeburgesch' => 'lb',
	'Luba-Katanga' => 'lu',
	'Ganda' => 'lg',
	'Macedonian' => 'mk',
	'Marshallese' => 'mh',
	'Malayalam' => 'ml',
	'Maori' => 'mi',
	'Marathi' => 'mr',
	'Malay' => 'ms',
	'Malagasy' => 'mg',
	'Maltese' => 'mt',
	'Moldavian' => 'mo',
	'Mongolian' => 'mn',
	'Nauru' => 'na',
	'Navajo' => 'nv',
	'Navaho' => 'nv',
	'Ndebele, South' => 'nr',
	'South Ndebele' => 'nr',
	'Ndebele, North' => 'nd',
	'North Ndebele' => 'nd',
	'Ndonga' => 'ng',
	'Nepali' => 'ne',
	'Norwegian Nynorsk' => 'nn',
	'Norwegian Bokmal' => 'nb',
	'Norwegian' => 'no',
	'Chichewa' => 'ny',
	'Chewa' => 'ny',
	'Nyanja' => 'ny',
	'Occitan (post 1500)' => 'oc',
	'Provencal' => 'oc',
	'Ojibwa' => 'oj',
	'Oriya' => 'or',
	'Oromo' => 'om',
	'Ossetian' => 'os',
	'Ossetic' => 'os',
	'Panjabi' => 'pa',
	'Punjabi' => 'pa',
	'Persian' => 'fa',
	'Pali' => 'pi',
	'Polish' => 'pl',
	'Portuguese' => 'pt',
	'Pushto' => 'ps',
	'Quechua' => 'qu',
	'Raeto-Romance' => 'rm',
	'Romanian' => 'ro',
	'Rundi' => 'rn',
	'Russian' => 'ru',
	'Sango' => 'sg',
	'Sanskrit' => 'sa',
	'Serbian' => 'sr',
	'Croatian' => 'hr',
	'Sinhala' => 'si',
	'Sinhalese' => 'si',
	'Slovak' => 'sk',
	'Slovenian' => 'sl',
	'Northern Sami' => 'se',
	'Samoan' => 'sm',
	'Shona' => 'sn',
	'Sindhi' => 'sd',
	'Somali' => 'so',
	'Sotho, Southern' => 'st',
	'Spanish' => 'es',
	'Castilian' => 'es',
	'Sardinian' => 'sc',
	'Swati' => 'ss',
	'Sundanese' => 'su',
	'Swahili' => 'sw',
	'Swedish' => 'sv',
	'Tahitian' => 'ty',
	'Tamil' => 'ta',
	'Tatar' => 'tt',
	'Telugu' => 'te',
	'Tajik' => 'tg',
	'Tagalog' => 'tl',
	'Thai' => 'th',
	'Tibetan' => 'bo',
	'Tigrinya' => 'ti',
	'Tonga (Tonga Islands)' => 'to',
	'Tswana' => 'tn',
	'Tsonga' => 'ts',
	'Turkmen' => 'tk',
	'Turkish' => 'tr',
	'Twi' => 'tw',
	'Uighur' => 'ug',
	'Uyghur' => 'ug',
	'Ukrainian' => 'uk',
	'Urdu' => 'ur',
	'Uzbek' => 'uz',
	'Venda' => 've',
	'Vietnamese' => 'vi',
	'Volapuk' => 'vo',
	'Welsh' => 'cy',
	'Walloon' => 'wa',
	'Wolof' => 'wo',
	'Xhosa' => 'xh',
	'Yiddish' => 'yi',
	'Yoruba' => 'yo',
	'Zhuang' => 'za',
	'Chuang' => 'za',
	'Zulu' => 'zu',
);

$country_code = array(
    'United States' => 'US',
	'Afghanistan' => 'AF',
    'Aland Islands' => 'AX',
    'Albania' => 'AL',
    'Algeria' => 'DZ',
    'American Samoa' => 'AS',
    'Andorra' => 'AD',
    'Angola' => 'AO',
    'Anguilla' => 'AI',
    'Antarctica' => 'AQ',
    'Antigua and Barbuda' => 'AG',
    'Argentina' => 'AR',
    'Armenia' => 'AM',
    'Aruba' => 'AW',
    'Australia' => 'AU',
    'Austria' => 'AT',
    'Azerbaijan' => 'AZ',
    'Bahamas' => 'BS',
    'Bahrain' => 'BH',
    'Bangladesh' => 'BD',
    'Barbados' => 'BB',
    'Belarus' => 'BY',
    'Belgium' => 'BE',
    'Belize' => 'BZ',
    'Benin' => 'BJ',
    'Bermuda' => 'BM',
    'Bhutan' => 'BT',
    'Bolivia' => 'BO',
    'Bosnia and Herzegovina' => 'BA',
    'Botswana' => 'BW',
    'Bouvet Island' => 'BV',
    'Brazil' => 'BR',
    'British Indian Ocean Territory' => 'IO',
    'British Virgin Islands' => 'VG',
    'Brunei' => 'BN',
    'Bulgaria' => 'BG',
    'Burkina Faso' => 'BF',
    'Burundi' => 'BI',
    'Cambodia' => 'KH',
    'Cameroon' => 'CM',
    'Canada' => 'CA',
    'Cape Verde' => 'CV',
    'Cayman Islands' => 'KY',
    'Central African Republic' => 'CF',
    'Chad' => 'TD',
    'Chile' => 'CL',
    'China' => 'CN',
    'Christmas Island' => 'CX',
    'Cocos (Keeling) Islands' => 'CC',
    'Colombia' => 'CO',
    'Comoros' => 'KM',
    'Congo' => 'CG',
    'Cook Islands' => 'CK',
    'Costa Rica' => 'CR',
    'Cote d\'Ivoire' => 'CI',
    'Croatia' => 'HR',
    'Cuba' => 'CU',
    'Cyprus' => 'CY',
    'Czech Republic' => 'CZ',
    'Democratic Republic of the Congo' => 'CD',
    'Denmark' => 'DK',
    'Djibouti' => 'DJ',
    'Dominica' => 'DM',
    'Dominican Republic' => 'DO',
    'East Timor' => 'TL',
    'Ecuador' => 'EC',
    'Egypt' => 'EG',
    'El Salvador' => 'SV',
    'Equatorial Guinea' => 'GQ',
    'Eritrea' => 'ER',
    'Estonia' => 'EE',
    'Ethiopia' => 'ET',
    'Falkland Islands' => 'FK',
    'Faroe Islands' => 'FO',
    'Federated States of Micronesia' => 'FM',
    'Fiji' => 'FJ',
    'Finland' => 'FI',
    'France' => 'FR',
    'French Guiana' => 'GF',
    'French Polynesia' => 'PF',
    'French Southern Territories' => 'TF',
    'Gabon' => 'GA',
    'Gambia' => 'GM',
    'Georgia' => 'GE',
    'Germany' => 'DE',
    'Ghana' => 'GH',
    'Gibraltar' => 'GI',
    'Greece' => 'GR',
    'Greenland' => 'GL',
    'Grenada' => 'GD',
    'Guernsey' => 'GG',
    'Guadeloupe' => 'GP',
    'Guam' => 'GU',
    'Guatemala' => 'GT',
    'Guinea-Bissau' => 'GW',
    'Guinea' => 'GN',
    'Guyana' => 'GY',
    'Haiti' => 'HT',
    'Heard Island and McDonald Islands' => 'HM',
    'Honduras' => 'HN',
    'Hong Kong' => 'HK',
    'Hungary' => 'HU',
    'Iceland' => 'IS',
    'India' => 'IN',
    'Indonesia' => 'ID',
    'Iran' => 'IR',
    'Iraq' => 'IQ',
    'Ireland' => 'IE',
    'Israel' => 'IL',
    'Isle of Man' => 'IM',
    'Italy' => 'IT',
    'Jersey' => 'JE',
    'Jamaica' => 'JM',
    'Japan' => 'JP',
    'Jordan' => 'JO',
    'Kazakhstan' => 'KZ',
    'Kenya' => 'KE',
    'Kiribati' => 'KI',
    'Kuwait' => 'KW',
    'Kyrgyzstan' => 'KG',
    'Laos' => 'LA',
    'Latvia' => 'LV',
    'Lebanon' => 'LB',
    'Lesotho' => 'LS',
    'Liberia' => 'LR',
    'Libya' => 'LY',
    'Liechtenstein' => 'LI',
    'Lithuania' => 'LT',
    'Luxembourg' => 'LU',
    'Macao' => 'MO',
    'Madagascar' => 'MG',
    'Malawi' => 'MW',
    'Malaysia' => 'MY',
    'Maldives' => 'MV',
    'Mali' => 'ML',
    'Malta' => 'MT',
    'Marshall Islands' => 'MH',
    'Martinique' => 'MQ',
    'Mauritania' => 'MR',
    'Mauritius' => 'MU',
    'Mayotte' => 'YT',
    'Mexico' => 'MX',
    'Moldova' => 'MD',
    'Monaco' => 'MC',
    'Mongolia' => 'MN',
    'Montserrat' => 'MS',
    'Morocco' => 'MA',
    'Mozambique' => 'MZ',
    'Myanmar' => 'MM',
    'Namibia' => 'NA',
    'Nauru' => 'NR',
    'Nepal' => 'NP',
    'Netherlands' => 'NL',
    'Netherlands Antilles' => 'AN',
    'New Caledonia' => 'NC',
    'New Zealand' => 'NZ',
    'Nicaragua' => 'NI',
    'Nigeria' => 'NG',
    'Niger' => 'NE',
    'Niue' => 'NU',
    'Norfolk Island' => 'NF',
    'North Korea' => 'KP',
    'Northern Mariana Islands' => 'MP',
    'Norway' => 'NO',
    'Oman' => 'OM',
    'Pakistan' => 'PK',
    'Palau' => 'PW',
    'Palestinian Territories' => 'PS',
    'Panama' => 'PA',
    'Papua New Guinea' => 'PG',
    'Paraguay' => 'PY',
    'Peru' => 'PE',
    'Philippines' => 'PH',
    'Pitcairn Islands' => 'PN',
    'Poland' => 'PL',
    'Portugal' => 'PT',
    'Puerto Rico' => 'PR',
    'Qatar' => 'QA',
    'Reunion' => 'RE',
    'Republic of Macedonia' => 'MK',
    'Romania' => 'RO',
    'Russia' => 'RU',
    'Rwanda' => 'RW',
    'Saint Helena' => 'SH',
    'Saint Kitts and Nevis' => 'KN',
    'Saint Lucia' => 'LC',
    'Saint-Pierre and Miquelon' => 'PM',
    'Saint Vincent and the Grenadines' => 'VC',
    'Samoa' => 'WS',
    'San Marino' => 'SM',
    'Sao Tome and Principe' => 'ST',
    'Saudi Arabia' => 'SA',
    'Senegal' => 'SN',
    'Serbia and Montenegro' => 'CS',
    'Seychelles' => 'SC',
    'Sierra Leone' => 'SL',
    'Singapore' => 'SG',
    'Slovakia' => 'SK',
    'Slovenia' => 'SI',
    'Solomon Islands' => 'SB',
    'Somalia' => 'SO',
    'South Africa' => 'ZA',
    'South Georgia and the South Sandwich Islands' => 'GS',
    'South Korea' => 'KR',
    'Spain' => 'ES',
    'Sri Lanka' => 'LK',
    'Sudan' => 'SD',
    'Suriname' => 'SR',
    'Svalbard' => 'SJ',
    'Swaziland' => 'SZ',
    'Sweden' => 'SE',
    'Switzerland' => 'CH',
    'Syria' => 'SY',
    'Taiwan' => 'TW',
    'Tajikistan' => 'TJ',
    'Tanzania' => 'TZ',
    'Thailand' => 'TH',
    'Togo' => 'TG',
    'Tokelau' => 'TK',
    'Tonga' => 'TO',
    'Trinidad and Tobago' => 'TT',
    'Tunisia' => 'TN',
    'Turkey' => 'TR',
    'Turkmenistan' => 'TM',
    'Turks and Caicos Islands' => 'TC',
    'Tuvalu' => 'TV',
    'Uganda' => 'UG',
    'Ukraine' => 'UA',
    'United Arab Emirates' => 'AE',
    'United Kingdom' => 'GB',
    'United States Minor Outlying Islands' => 'UM',
    'Uruguay' => 'UY',
    'U.S. Virgin Islands' => 'VI',
    'Uzbekistan' => 'UZ',
    'Vanuatu' => 'VU',
    'Vatican City' => 'VA',
    'Venezuela' => 'VE',
    'Vietnam' => 'VN',
    'Wallis and Futuna' => 'WF',
    'Western Sahara' => 'EH',
    'Yemen' => 'YE',
    'Zambia' => 'ZM',
    'Zimbabwe' => 'ZW',
);

$timezones = array(
	'Africa/Abidjan',
	'Africa/Accra',
	'Africa/Addis Ababa',
	'Africa/Algiers',
	'Africa/Asmera',
	'Africa/Bamako',
	'Africa/Bangui',
	'Africa/Banjul',
	'Africa/Bissau',
	'Africa/Blantyre',
	'Africa/Brazzaville',
	'Africa/Bujumbura',
	'Africa/Cairo',
	'Africa/Casablanca',
	'Africa/Ceuta',
	'Africa/Conakry',
	'Africa/Dakar',
	'Africa/Dar es Salaam',
	'Africa/Djibouti',
	'Africa/Douala',
	'Africa/El Aaiun',
	'Africa/Freetown',
	'Africa/Gaborone',
	'Africa/Harare',
	'Africa/Johannesburg',
	'Africa/Kampala',
	'Africa/Khartoum',
	'Africa/Kigali',
	'Africa/Kinshasa',
	'Africa/Lagos',
	'Africa/Libreville',
	'Africa/Lome',
	'Africa/Luanda',
	'Africa/Lubumbashi',
	'Africa/Lusaka',
	'Africa/Malabo',
	'Africa/Maputo',
	'Africa/Maseru',
	'Africa/Mbabane',
	'Africa/Mogadishu',
	'Africa/Monrovia',
	'Africa/Nairobi',
	'Africa/Ndjamena',
	'Africa/Niamey',
	'Africa/Nouakchott',
	'Africa/Ouagadougou',
	'Africa/Porto-Novo',
	'Africa/Sao Tome',
	'Africa/Timbuktu',
	'Africa/Tripoli',
	'Africa/Tunis',
	'Africa/Windhoek',
	'America/Adak',
	'America/Anchorage',
	'America/Anguilla',
	'America/Antigua',
	'America/Araguaina',
	'America/Aruba',
	'America/Asuncion',
	'America/Barbados',
	'America/Belem',
	'America/Belize',
	'America/Boa Vista',
	'America/Bogota',
	'America/Boise',
	'America/Buenos Aires',
	'America/Cambridge Bay',
	'America/Cancun',
	'America/Caracas',
	'America/Catamarca',
	'America/Cayenne',
	'America/Cayman',
	'America/Chicago',
	'America/Chihuahua',
	'America/Cordoba',
	'America/Costa Rica',
	'America/Cuiaba',
	'America/Curacao',
	'America/Dawson',
	'America/Dawson Creek',
	'America/Denver',
	'America/Detroit',
	'America/Dominica',
	'America/Edmonton',
	'America/Eirunepe',
	'America/El Salvador',
	'America/Fortaleza',
	'America/Glace Bay',
	'America/Godthab',
	'America/Goose Bay',
	'America/Grand Turk',
	'America/Grenada',
	'America/Guadeloupe',
	'America/Guatemala',
	'America/Guayaquil',
	'America/Guyana',
	'America/Halifax',
	'America/Havana',
	'America/Hermosillo',
	'America/Indiana/Knox',
	'America/Indiana/Marengo',
	'America/Indiana/Vevay',
	'America/Indianapolis',
	'America/Inuvik',
	'America/Iqaluit',
	'America/Jamaica',
	'America/Jujuy',
	'America/Juneau',
	'America/Kentucky/Louisville',
	'America/Kentucky/Monticello',
	'America/La Paz',
	'America/Lima',
	'America/Los Angeles',
	'America/Maceio',
	'America/Managua',
	'America/Manaus',
	'America/Martinique',
	'America/Mazatlan',
	'America/Mendoz',
	'America/Menominee',
	'America/Merida',
	'America/Mexico City',
	'America/Miquelon',
	'America/Monterrey',
	'America/Montevideo',
	'America/Montreal',
	'America/Montserrat',
	'America/Nassau',
	'America/New York',
	'America/Nipigon',
	'America/Nome',
	'America/Noronha',
	'America/Panama',
	'America/Pangnirtung',
	'America/Paramaribo',
	'America/Phoenix',
	'America/Port-au-Prince',
	'America/Porto Velho',
	'America/Port of Spain',
	'America/Puerto Rico',
	'America/Rainy River',
	'America/Rankin Inlet',
	'America/Recife',
	'America/Regina',
	'America/Rio Branco',
	'America/Rosario',
	'America/Santiago',
	'America/Santo Domingo',
	'America/Sao Paulo',
	'America/Scoresbysund',
	'America/Shiprock',
	'America/St Johns',
	'America/St Kitts',
	'America/St Lucia',
	'America/St Thomas',
	'America/St Vincent',
	'America/Swift Current',
	'America/Tegucigalpa',
	'America/Thule',
	'America/Thunder Bay',
	'America/Tijuana',
	'America/Tortola',
	'America/Vancouver',
	'America/Whitehorse',
	'America/Winnipeg',
	'America/Yakutat',
	'America/Yellowknife',
	'Antarctica/Casey',
	'Antarctica/Davis',
	'Antarctica/DumontDUrville',
	'Antarctica/Mawson',
	'Antarctica/McMurdo',
	'Antarctica/Palmer',
	'Antarctica/South Pole',
	'Antarctica/Syowa',
	'Antarctica/Vostok',
	'Arctic/Longyearbyen',
	'Asia/Aden',
	'Asia/Almaty',
	'Asia/Amman',
	'Asia/Anadyr',
	'Asia/Aqtau',
	'Asia/Aqtobe',
	'Asia/Ashgabat',
	'Asia/Baghdad',
	'Asia/Bahrain',
	'Asia/Baku',
	'Asia/Bangkok',
	'Asia/Beirut',
	'Asia/Bishkek',
	'Asia/Brunei',
	'Asia/Calcutta',
	'Asia/Chungking',
	'Asia/Colombo',
	'Asia/Damascus',
	'Asia/Dhaka',
	'Asia/Dili',
	'Asia/Dubai',
	'Asia/Dushanbe',
	'Asia/Gaza',
	'Asia/Harbin',
	'Asia/Hong Kong',
	'Asia/Hovd',
	'Asia/Irkutsk',
	'Asia/Jakarta',
	'Asia/Jayapura',
	'Asia/Jerusalem',
	'Asia/Kabul',
	'Asia/Kamchatka',
	'Asia/Karachi',
	'Asia/Kashgar',
	'Asia/Katmandu',
	'Asia/Krasnoyarsk',
	'Asia/Kuala Lumpur',
	'Asia/Kuching',
	'Asia/Kuwait',
	'Asia/Macao',
	'Asia/Magadan',
	'Asia/Manila',
	'Asia/Muscat',
	'Asia/Nicosia',
	'Asia/Novosibirsk',
	'Asia/Omsk',
	'Asia/Phnom Penh',
	'Asia/Pyongyang',
	'Asia/Qatar',
	'Asia/Rangoon',
	'Asia/Riyadh',
	'Asia/Saigon',
	'Asia/Samarkand',
	'Asia/Seoul',
	'Asia/Shanghai',
	'Asia/Singapore',
	'Asia/Taipei',
	'Asia/Tashkent',
	'Asia/Tbilisi',
	'Asia/Tehran',
	'Asia/Thimphu',
	'Asia/Tokyo',
	'Asia/Ujung Pandang',
	'Asia/Ulaanbaatar',
	'Asia/Urumqi',
	'Asia/Vientiane',
	'Asia/Vladivostok',
	'Asia/Yakutsk',
	'Asia/Yekaterinburg',
	'Asia/Yerevan',
	'Atlantic/Azores',
	'Atlantic/Bermuda',
	'Atlantic/Canary',
	'Atlantic/Cape Verde',
	'Atlantic/Faeroe',
	'Atlantic/Jan Mayen',
	'Atlantic/Madeira',
	'Atlantic/Reykjavik',
	'Atlantic/South Georgia',
	'Atlantic/Stanley',
	'Atlantic/St Helena',
	'Australia/Adelaide',
	'Australia/Brisbane',
	'Australia/Broken Hill',
	'Australia/Darwin',
	'Australia/Hobart',
	'Australia/Lindeman',
	'Australia/Lord Howe',
	'Australia/Melbourne',
	'Australia/Perth',
	'Australia/Sydney',
	'Europe/Amsterdam',
	'Europe/Andorra',
	'Europe/Athens',
	'Europe/Belfast',
	'Europe/Belgrade',
	'Europe/Berlin',
	'Europe/Bratislava',
	'Europe/Brussels',
	'Europe/Bucharest',
	'Europe/Budapest',
	'Europe/Chisinau',
	'Europe/Copenhagen',
	'Europe/Dublin',
	'Europe/Gibraltar',
	'Europe/Helsinki',
	'Europe/Istanbul',
	'Europe/Kaliningrad',
	'Europe/Kiev',
	'Europe/Lisbon',
	'Europe/Ljubljana',
	'Europe/London',
	'Europe/Luxembourg',
	'Europe/Madrid',
	'Europe/Malta',
	'Europe/Minsk',
	'Europe/Monaco',
	'Europe/Moscow',
	'Europe/Oslo',
	'Europe/Paris',
	'Europe/Prague',
	'Europe/Riga',
	'Europe/Rome',
	'Europe/Samara',
	'Europe/San Marino',
	'Europe/Sarajevo',
	'Europe/Simferopol',
	'Europe/Skopje',
	'Europe/Sofia',
	'Europe/Stockholm',
	'Europe/Tallinn',
	'Europe/Tirane',
	'Europe/Uzhgorod',
	'Europe/Vaduz',
	'Europe/Vatican',
	'Europe/Vienna',
	'Europe/Vilnius',
	'Europe/Warsaw',
	'Europe/Zagreb',
	'Europe/Zaporozhye',
	'Europe/Zurich',
	'Indian/Antananarivo',
	'Indian/Chagos',
	'Indian/Christmas',
	'Indian/Cocos',
	'Indian/Comoro',
	'Indian/Kerguelen',
	'Indian/Mahe',
	'Indian/Maldives',
	'Indian/Mauritius',
	'Indian/Mayotte',
	'Indian/Reunion',
	'Pacific/Apia',
	'Pacific/Auckland',
	'Pacific/Chatham',
	'Pacific/Easter',
	'Pacific/Efate',
	'Pacific/Enderbury',
	'Pacific/Fakaofo',
	'Pacific/Fiji',
	'Pacific/Funafuti',
	'Pacific/Galapagos',
	'Pacific/Gambier',
	'Pacific/Guadalcanal',
	'Pacific/Guam',
	'Pacific/Honolulu',
	'Pacific/Johnston',
	'Pacific/Kiritimati',
	'Pacific/Kosrae',
	'Pacific/Kwajalein',
	'Pacific/Majuro',
	'Pacific/Marquesas',
	'Pacific/Midway',
	'Pacific/Nauru',
	'Pacific/Niue',
	'Pacific/Norfolk',
	'Pacific/Noumea',
	'Pacific/Pago Pago',
	'Pacific/Palau',
	'Pacific/Pitcairn',
	'Pacific/Ponape',
	'Pacific/Port Moresby',
	'Pacific/Rarotonga',
	'Pacific/Saipan',
	'Pacific/Tahiti',
	'Pacific/Tarawa',
	'Pacific/Tongatapu',
	'Pacific/Truk',
	'Pacific/Wake',
	'Pacific/Wallis',
	'Pacific/Yap');



?>

<style>
#ssi {
	padding: 1em;
	margin-left: auto;
	margin-right: auto;
	width: 45em;
}
#message {
	padding: .5em;
	border: 1px solid gray;
	background-color: lightblue;
	width: 45em;
}


</style>
<h2>Simple Sign In</h2>
<div id="ssi">
<?php if($message): ?>
<div id="message">
<?php echo $message; ?>
</div>
<?php elseif($error): ?>
<div id="message">
<?php echo $error; ?>
</div>
<?php endif; ?>


<form action="" method="post">
<dl>
	<?php if($user_select && !isset($edit_login_info)): ?>
	<dt><label for="edit_id">Edit a login:</label></dt>
    <dd>
		<select name="edit_id">
		<?php foreach($user_select AS $user): ?>
		<option value="<?php echo $user->id; ?>"><?php echo $user->login_nick; ?></option>
		<?php endforeach; ?>
		</select>
		<input type="submit" id="edit_id_submit" name="edit_id_submit" value="Edit Login" />
	</dd>
	
	<?php endif;?>
	
	<?php if(!isset($edit_login_info)): ?>
	<dt><label for="login_nick">Login Nick:</label></dt>
    <dd>
		<?php 
		if($_POST['login_nick'] && isset($error)) {
			$value = wp_specialchars($_POST['login_nick']);
		} else {
			$value = '';
		}
		
		?>
		<input type="text" id="login_nick" name="login_nick" value="<?php echo $value;?>" />@<?php echo $domain ?>
	</dd>
	<?php else: ?>
	<h3>Editing: <?php echo $edit_login_info->login_nick ?>@<?php echo $domain ?></h3>
	<?php endif; ?>

	<dt><label for="display_nick">Display Nick:</label></dt>
    <dd>
		<?php 
		if (isset($edit_login_info)) { 
			$value = $edit_login_info->display_nick;
		} else if($_POST['display_nick'] && isset($error)) {
			$value = wp_specialchars($_POST['display_nick']);
		} else {
			$value = '';
		}
		
		?>
		<input type="text" id="display_nick" name="display_nick" value="<?php echo $value;?>" />
	</dd>

    <dt><label for="email">Avatar Uri:</label></dt>
    <dd>
		<?php 
		if (isset($edit_login_info)) { 
			$value = $edit_login_info->avatar_uri;
		} else if($_POST['avatar_uri'] && isset($error)) {
			$value = wp_specialchars($_POST['avatar_uri']);
		} else {
			$value = '';
		}
		
		?>
		<input type="text" id="avatar_uri" name="avatar_uri" value="<?php echo $value;?>" />
	</dd>
	
	<dt><label for="email">Email Address:</label></dt>
    <dd>
		<?php 
		if (isset($edit_login_info)) { 
			$value = $edit_login_info->email;
		} else if($_POST['email'] && isset($error)) {
			$value = wp_specialchars($_POST['email']);
		} else {
			$value = '';
		}
		
		?>
		<input type="text" id="email" name="email" value="<?php echo $value; ?>" />
	</dd>
	
	<dt><label for="language">Language:</label></dt>
    <dd>
		<?php 
		if (isset($edit_login_info)) { 
			$loaded_value = $edit_login_info->language;
		} else if($_POST['language'] && isset($error)) {
			$loaded_value = wp_specialchars($_POST['language']);
		} else {
			$loaded_value = '';
		}
		
		?>
		<select name="language">
		<?php foreach($language_code AS $name => $value): ?>
		
		<option value="<?php echo $value ?>" <?php echo ($loaded_value == $value) ? 'selected = "selected"' : ''; ?>>
		<?php echo $name; ?></option>
		
		<?php endforeach; ?>
		</select>
	</dd>
	
	<dt><label for="country">Country:</label></dt>
    <dd>
		<?php 
		if (isset($edit_login_info)) { 
			$loaded_value = $edit_login_info->country;
		} else if($_POST['country'] && isset($error)) {
			$loaded_value = wp_specialchars($_POST['country']);
		} else {
			$loaded_value = '';
		}
		
		?>
		<select name="country">
		<?php foreach($country_code AS $name => $value): ?>
		
		<option value="<?php echo $value ?>" <?php echo ($loaded_value == $value) ? 'selected = "selected"' : ''; ?>>
		<?php echo $name; ?></option>
		
		<?php endforeach; ?>
		</select>
	</dd>
	
	<dt><label for="timezone">Timezone:</label></dt>
    <dd>
		<?php 
		if (isset($edit_login_info)) { 
			$loaded_value = $edit_login_info->timezone;
		} else if($_POST['timezone'] && isset($error)) {
			$loaded_value = wp_specialchars($_POST['timezone']);
		} else {
			$loaded_value = '';
		}
		
		?>
		<select name="timezone">
		<?php foreach($timezones AS $timezone): ?>
		
		<option value="<?php echo $timezone ?>" <?php echo ($loaded_value == $timezone) ? 'selected = "selected"' : ''; ?>>
		<?php echo $timezone; ?></option>
		
		<?php endforeach; ?>
		</select>
	</dd>
	
	<?php if(!isset($edit_login_info)): ?>
    <dd><input type="submit" id="new_login_submit" name="new_login_submit" value="Create Login" />
	<?php else: ?>
	<input type="hidden" id="edit_id_hidden" name="edit_id" value="<?php echo $edit_login_info->id; ?>" />
	<dd><input type="submit" id="edit_submit" name="edit_submit" value="Save Login" />
	<input type="submit" id="delete_submit" name="delete_submit" value="Delete Login"  onclick="return confirm('Warning: Upon deletion you will not be able to login to any sites as <?php echo $edit_login_info->login_nick ?>@<?php echo $domain ?>! Are you sure you want to delete the login?');" />
	<input type="submit" id="cancel_edit_submit" name="cancel_edit_submit" value="Cancel" />
	</dd>
	<?php endif; ?>
</dl>
</form>
</div>
